services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopper-api
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=shopperdb
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shopper-frontend
    ports:
      - "80:80"
    environment:
      - VITE_GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - VITE_API_URL=http://backend:8080
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:17-alpine
    container_name: shopper-db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shopperdb
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:


networks:
  app-network:
    driver: bridge
